export const EventConstants = {
    JOIN_GAME_SUCCESS: "JOIN_GAME_SUCCESS",
    MINUS_BUTTON_CLICK: "MINUS_BUTTON_CLICK",
    PLUS_BUTTON_CLICK: "PLUS_BUTTON_CLICK",
    SPIN_BUTTON_CLICK: "SPIN_BUTTON_CLICK",
    SPIN_START: "SPIN_START",
    SPIN_REQUEST: "SPIN_REQUEST",
    CALCULATE_WALLET: "CALCULATE_WALLET"
}